name: Verify CMSIS Compliance

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 6 * * 7'

jobs:
  verify-cmsis-compliance-example4_mps2_multi_devices:
    name: Verify CMSIS Compliance example4_mps2_multi_devices
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Arm-Examples/verify-cmsis-example-action@latest
        name: Verify CMSIS Compliance example4_mps2_multi_devices
        with:
          branch: ${{ github.ref }}
          project-file: ./example4_mps2_multi_devices/coremark.csolution.yml
          API_TOKEN: ${{ secrets.CMSIS_API_KEY }}
          output-artifact: output-example4_mps2_multi_devices
