name: Verify CMSIS Compliance

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 6 * * 0'

jobs:
  verify-cmsis-compliance-example3_cm4_mps2_an386:
    name: Verify CMSIS Compliance example3_cm4_mps2_an386
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Arm-Examples/verify-cmsis-example-action@latest
        name: Verify CMSIS Compliance example3_cm4_mps2_an386
        with:
          branch: ${{ github.ref }}
          project-file: ./example3_cm4_mps2_an386/coremark.csolution.yml
          API_TOKEN: ${{ secrets.CMSIS_API_KEY }}
          output-artifact: output-example3_cm4_mps2_an386
