name: Verify CMSIS Compliance

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 6 * * 0'

jobs:
  verify-cmsis-compliance-example5_multi_projects:
    name: Verify CMSIS Compliance example5_multi_projects
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Arm-Examples/verify-cmsis-example-action@latest
        name: Verify CMSIS Compliance example5_multi_projects
        with:
          branch: ${{ github.ref }}
          project-file: ./example5_multi_projects/coremark-pro.csolution.yml
          API_TOKEN: ${{ secrets.CMSIS_API_KEY }}
          output-artifact: output-example5_multi_projects
